/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TP2;

import org.junit.Assert;
import org.junit.Test;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import static junit.framework.TestCase.assertTrue;

public class TableroTest {
    @Test public void testTableroEsCreadoCorrectamenteConAltoYAncho() {
        Jugador jugador1 = new Jugador();
        Jugador jugador2 = new Jugador();
        Integer ancho = 20;
        Integer alto = 20;

        Tablero tablero = new Tablero( ancho, alto, jugador1, jugador2);

        Assert.assertEquals(new BigDecimal(20), new BigDecimal(tablero.getAncho()));
        Assert.assertEquals(new BigDecimal(20), new BigDecimal(tablero.getAlto()));
    }

    @Test public void testTableroEsCreadoCorrectamenteConDosSectores(){
        Jugador jugador1 = new Jugador();
        Jugador jugador2 = new Jugador();
        Integer ancho = 20;
        Integer alto = 20;

        Tablero tablero = new Tablero( ancho, alto, jugador1, jugador2);

        Sector sector1 = tablero.getSector1();
        Sector sector2 = tablero.getSector2();

        assertTrue(sector1 instanceof Sector);
        assertTrue(sector2 instanceof Sector);
    }
}

