/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TP2;
import java.util.*;

public class Tablero {

    private List<Fila> sector1; //1 a 10
    private List<Fila> sector2; //11 a 20

    public Tablero(){

        for(int i = 0; i < 10; ++i) {
            sector1.add(new Fila());
        }

        for(int i = 0; i < 10; ++i) {
            sector2.add(new Fila());
        }
    }

    public int getLargoSector1() {
        return (sector1).size();
    }

    public int getLargoSector2() {
        return (sector2).size();
    }

    public boolean colocarPieza(int sectorDelJugador, int fila){

        if(sectorDelJugador == 1 && fila > 10 || sectorDelJugador == 2 && fila < 10){
            return false;
        }
        return true;
    }

}
